services:
  blog-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/mysite
    environment:
      - DB_HOST=database
      - DB_NAME=blog
      - DB_USER=blog
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database


  database:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=pass
    ports:
      - "54331:5432"